import type { HeroPhoto } from "@/components/hero-photo-strip"

// This file is auto-generated by scripts/sync-cloudinary.mjs
// Run the sync script whenever you upload new hero photos to Cloudinary.
export const heroPhotos: HeroPhoto[] = [
  {
    src: "https://res.cloudinary.com/dyqdtpd3b/image/upload/f_auto,q_auto,w_800/IMG_1564-566_gldg6s.jpg",
    width: 3024,
    height: 4032,
  },
]
