import type { Skill } from "./types"

export const skills: Skill[] = [
  // [REPLACE] Edit these to match your actual stack
  { name: "Python", category: "language" },
  { name: "JavaScript", category: "language" },
  { name: "TypeScript", category: "language" },
  { name: "R", category: "language" },
  { name: "HTML / CSS", category: "language" },
  { name: "SQL", category: "language" },
  { name: "C++ / C# / C", category: "language" },
  { name: "PHP", category: "language" },
  { name: "F#", category: "language" },
  { name: "Node.js", category: "framework" },
  { name: "PyTorch", category: "framework" },
  { name: "TensorFlow", category: "framework" },
  { name: "Pandas", category: "framework" },
  { name: "Numpy", category: "framework" },
  { name: "Next.js", category: "framework" },
  { name: "scikit-learn", category: "framework" },
  { name: "React", category: "framework" },
  { name: "HuggingFace", category: "framework" },
  { name: "Git", category: "tool" },
  { name: "Docker", category: "tool" },
  { name: "Jupyter", category: "tool" },
  { name: "REST APIs", category: "tool" },
  { name: "Kubernetes", category: "tool" },
  { name: "MongoDB", category: "tool" },
  { name: "MySQL", category: "tool" },
  { name: "PostgreSQL", category: "tool" },
  { name: "Vercel", category: "platform" },
  { name: "GitHub", category: "platform" },
  { name: "Supabase", category: "platform" },
  { name: "Linux", category: "platform" },
  { name: "Render", category: "platform" },
  { name: "Cloudinary", category: "platform" },
  { name: "AWS", category: "platform" },
]
